Bandage:
  Material: PAPER
  Warmup-Speed: 1.55
  Result-Amount: 2
  ModelData: 16
  Name: '&4✚&fBandage&4✚'
  Lore:
  - '&6Right/Left click to use this Bandage'
  - '&6Because smeths is cool'
  Regen-Time: 3
  Regen-Amplifier: 1
  Crafting-Material-top-left: AIR
  Crafting-Material-top-middle: PAPER
  Crafting-Material-top-right: AIR
  Crafting-Material-middle-left: PAPER
  Crafting-Material-center: PAPER
  Crafting-Material-middle-right: PAPER
  Crafting-Material-bottom-left: AIR
  Crafting-Material-bottom-middle: PAPER
  Crafting-Material-bottom-right: AIR
  PerformCMD: false
  ConsoleCMD: true
  CMD: 'tell [playername] your server admin did not configure this plugin'
  NoPermCraft: 'No Permissions: you need baanage.craft'
  NoPermUse: 'No Permissions: you need bandage.use'
MedKit:
  Material: PAPER
  Warmup-Speed: 0.42
  Result-Amount: 1
  ModelData: 18
  Name: '&c✚&fMedKit&c✚'
  Lore:
  - '&6Right/Left click to use this MedKit'
  - '&6Because floris is cool'
  Regen-Time: 6
  Regen-Amplifier: 2
  Crafting-Material-top-left: PAPER
  Crafting-Material-top-middle: PAPER
  Crafting-Material-top-right: PAPER
  Crafting-Material-middle-left: PAPER
  Crafting-Material-center: PAPER
  Crafting-Material-middle-right: PAPER
  Crafting-Material-bottom-left: PAPER
  Crafting-Material-bottom-middle: PAPER
  Crafting-Material-bottom-right: PAPER
  PerformCMD: false
  ConsoleCMD: true
  CMD: 'tell [playername] your server admin did not configure this plugin'
  NoPermCraft: 'No Permissions: you need medkit.craft'
  NoPermUse: 'No Permissions: you need medkit.use'
