Bandage:
  Material: PAPER
  Warmup-Speed: 1
  Result-Amount: 2
  movecancel-threshhold: 0.75D
  ModelData: 16
  Name: '&4✚&fBandage&4✚'
  Regen-Time: 3
  Regen-Amplifier: 1
  Crafting-Material-top-left: AIR
  Crafting-Material-top-middle: PAPER
  Crafting-Material-top-right: AIR
  Crafting-Material-middle-left: PAPER
  Crafting-Material-center: PAPER
  Crafting-Material-middle-right: PAPER
  Crafting-Material-bottom-left: AIR
  Crafting-Material-bottom-middle: PAPER
  Crafting-Material-bottom-right: AIR
MedKit:
  Material: PAPER
  Warmup-Speed: 1
  Result-Amount: 1
  ModelData: 18
  Name: '&c✚&fMedKit&c✚'
  Regen-Time: 6
  Regen-Amplifier: 2
  Crafting-Material-top-left: PAPER
  Crafting-Material-top-middle: PAPER
  Crafting-Material-top-right: PAPER
  Crafting-Material-middle-left: PAPER
  Crafting-Material-center: PAPER
  Crafting-Material-middle-right: PAPER
  Crafting-Material-bottom-left: PAPER
  Crafting-Material-bottom-middle: PAPER
  Crafting-Material-bottom-right: PAPER
