name: MedCraft
main: me.smeths.and.rhetorical.MedCraft
author: smeths&rhetorical
version: 1.3.5.5
api-version: 1.13
permissions:
  bandage.craft:
    default: op
  bandage.use:
    default: op
  medkit.craft:
    default: op
  medkit.user:
    default: op