name: MedCraft
main: me.smeths.and.rhetorical.MedCraft
author: smeths&rhetorical
version: 1.3.5.3
api-version: 1.13
commands:
  MedCraft:
    description: MedCraft Command!
    usage: /MedCraft
    aliases: [meds]